# part:A Data preprocessing

#### step.1: Import the libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#### step.2:Import the data

In [2]:
df=pd.read_csv("breast cancer data.csv")
print(df)

           id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compa

In [3]:
df.describe()

id  radius_mean  texture_mean  perimeter_mean    area_mean  \
count  5.690000e+02   569.000000    569.000000      569.000000   569.000000   
mean   3.037183e+07    14.127292     19.289649       91.969033   654.889104   
std    1.250206e+08     3.524049      4.301036       24.298981   351.914129   
min    8.670000e+03     6.981000      9.710000       43.790000   143.500000   
25%    8.692180e+05    11.700000     16.170000       75.170000   420.300000   
50%    9.060240e+05    13.370000     18.840000       86.240000   551.100000   
75%    8.813129e+06    15.780000     21.800000      104.100000   782.700000   
max    9.113205e+08    28.110000     39.280000      188.500000  2501.000000   

       smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       symmetry_mean  ...  texture_worst  perimeter_worst   area_worst  \
count     569.000000  ...     569.000000       569.000000   569.000000   
mean        0.181162  ...      25.677223       107.261213   880.583128   
std         0.027414  ...       6.146258        33.602542   569.356993   
min         0.106000  ...      12.020000        50.410000   185.200000   
25%         0.161900  ...      21.080000        84.110000   515.300000   
50%         0.179200  ...      25.410000        97.660000   686.500000   
75%         0.195700  ...      29.720000       125.400000  1084.000000   
max         0.304000  ...      49.540000       251.200000  4254.000000   

       smoothness_worst  compactness_worst  concavity_worst  \
count        569.000000         569.000000       569.000000   
mean           0.132369           0.254265         0.272188   
std            0.022832           0.157336         0.208624   
min            0.071170           0.027290         0.000000   
25%            0.116600           0.147200         0.114500   
50%            0.131300           0.211900         0.226700   
75%            0.146000           0.339100         0.382900   
max            0.222600           1.058000         1.252000   

       concave points_worst  symmetry_worst  fractal_dimension_worst  \
count            569.000000      569.000000               569.000000   
mean               0.114606        0.290076                 0.083946   
std                0.065732        0.061867                 0.018061   
min                0.000000        0.156500                 0.055040   
25%                0.064930        0.250400                 0.071460   
50%                0.099930        0.282200                 0.080040   
75%                0.161400        0.317900                 0.092080   
max                0.291000        0.663800                 0.207500   

       Unnamed: 32  
count          0.0  
mean           NaN  
std            NaN  
min            NaN  
25%            NaN  
50%            NaN  
75%            NaN  
max            NaN  

[8 rows x 32 columns]

In [4]:
df.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed:

#### step3:Divide the dataset into input and output i.e Feature Matrix X and column vector Y

In [5]:
## here ID is not a feature of the data set so we can ignore it 
## and and we can also ignore the last column "unnamed:32" because no any data is given to it 
x=df.iloc[:,2:-1].values
y=df.iloc[:,1].values

In [6]:
print(x)
print(y)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
['M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'B' 'B' 'B' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'B' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'M'
 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B'
 'M' 'M' 'B' 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'M' 'M' 'M' 'B' 'B'
 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'B'
 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'M' 'B' 'M' 'M' 'B' 'B' 'B'
 'M' 'M' 'B' 'M' 'B' 'M' 'M' 'B' 'M' 'M' 'B' 'B' 'M' 'B' 'B' 'M' 'B' 'B'
 'B' 'B'

#### step.4:Taking care of categorical data

In [7]:
## only output(y) having categorical data
## Here is only two outcomes so we should use LableEncoder
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [8]:
print(y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 1 1 1 1 1 1 1 1 0 1 0 0 0 0 0 1 1 0 1 1 0 0 0 0 1 0 1 1 0 0 0 0 1 0 1 1
 0 1 0 1 1 0 0 0 1 1 0 1 1 1 0 0 0 1 0 0 1 1 0 0 0 1 1 0 0 0 0 1 0 0 1 0 0
 0 0 0 0 0 0 1 1 1 0 1 1 0 0 0 1 1 0 1 0 1 1 0 1 1 0 0 1 0 0 1 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 1 0 0 1 1 0 0 1 1 0 0 0 0 1 0 0 1 1 1 0 1
 0 1 0 0 0 1 0 0 1 1 0 1 1 1 1 0 1 1 1 0 1 0 1 0 0 1 0 1 1 1 1 0 0 1 1 0 0
 0 1 0 0 0 0 0 1 1 0 0 1 0 0 1 1 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 0 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 1 1 1 0 0
 0 0 1 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1
 1 0 1 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 1 0 0 0 0 0 1 0 0
 1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 1 0 1 0 0 1 

#### step.5:Taking care of missing data
-Ther is no any missing data

#### step.6:feature scaling using standarisation method

In [9]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
x=ss.fit_transform(x)


In [10]:
print(x)

[[ 1.09706398 -2.07333501  1.26993369 ...  2.29607613  2.75062224
   1.93701461]
 [ 1.82982061 -0.35363241  1.68595471 ...  1.0870843  -0.24388967
   0.28118999]
 [ 1.57988811  0.45618695  1.56650313 ...  1.95500035  1.152255
   0.20139121]
 ...
 [ 0.70228425  2.0455738   0.67267578 ...  0.41406869 -1.10454895
  -0.31840916]
 [ 1.83834103  2.33645719  1.98252415 ...  2.28998549  1.91908301
   2.21963528]
 [-1.80840125  1.22179204 -1.81438851 ... -1.74506282 -0.04813821
  -0.75120669]]


#### step.7:Spliting Data into training and testing set

In [11]:
from sklearn.model_selection import train_test_split
Xtrain,Xtest,Ytrain,Ytest=train_test_split(x,y ,test_size=0.2,random_state=1)

In [12]:
print(Xtrain)
print('\n')
print(Xtest)
print('\n')
print(Ytrain)
print('\n')
print(Ytest)

[[ 1.09706398  0.31888999  1.06398269 ...  1.26066751  0.25762232
   0.06008087]
 [ 1.75029663 -1.15181643  1.77657315 ...  0.72925926 -0.86835298
  -0.39709962]
 [-1.45622364 -1.13785403 -1.46674322 ... -1.53356538  0.14599546
  -0.32727569]
 ...
 [ 0.87269277  1.2171379   0.91569797 ...  1.14646802  0.66692082
   2.76825187]
 [-0.02763224  0.45618695 -0.08975482 ... -0.53256887 -1.09160671
  -0.43090327]
 [-0.31164643 -0.20237305 -0.38550046 ... -0.98175349 -1.47825627
  -1.2333243 ]]


[[ 0.15981713 -1.23559085  0.25747857 ... -0.05795583 -0.11932056
   0.45076239]
 [-0.27188444 -0.14652343 -0.24668948 ...  1.43425072  1.61655804
   1.88159879]
 [-0.33436757 -0.76086916 -0.36366965 ... -0.13713413  0.77531212
   0.65912586]
 ...
 [-1.44798723 -0.45602336 -1.36665103 ...  0.91959172  2.14719008
   1.85943247]
 [ 0.11437486  0.01171713  0.09395347 ... -0.28422307 -0.69525046
  -0.51624363]
 [-0.09863578 -0.8143917  -0.14824491 ... -1.24075791 -1.68533219
  -0.87810891]]


[1 1 0 0 0 0

# step.B:Fit the model

### 1.Logistic Regression method

###### step.1:Training the model

In [13]:
from sklearn.linear_model import LogisticRegression
lgr=LogisticRegression()
lgr.fit(Xtrain,Ytrain)

LogisticRegression()

###### step.2:Testind the model

In [14]:
Yest_lgr=lgr.predict(Xtest)
print(np.concatenate((Ytest.reshape(len(Ytest),1),Yest_lgr.reshape(len(Yest_lgr),1)),1))

[[0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]]


###### step.3:Finding Error

In [15]:
from sklearn.metrics import mean_absolute_error,mean_squared_error
print(f"Mean Absolute Error of the Logistic model is given as:{mean_absolute_error(Ytest,Yest_lgr)}")
print(f"Mean Squared Error of the Logistic model is given as:{mean_squared_error(Ytest,Yest_lgr)}")
print(f"Root Mean Squared Error of the Logistic model is given as:{np.sqrt(mean_squared_error(Ytest,Yest_lgr))}")

Mean Absolute Error of the Logistic model is given as:0.02631578947368421
Mean Squared Error of the Logistic model is given as:0.02631578947368421
Root Mean Squared Error of the Logistic model is given as:0.16222142113076254


###### step.4:Finding score/accuracy

In [16]:
from sklearn.metrics import confusion_matrix,precision_score,recall_score,accuracy_score,f1_score
print(f"confusion_matrix:\n {confusion_matrix(Ytest,Yest_lgr)}")
print(f"accuracy_score:{accuracy_score(Ytest,Yest_lgr)}")
print(f"precision_score:{precision_score(Ytest,Yest_lgr)}")
print(f"recall_score:{recall_score(Ytest,Yest_lgr)}")
print(f"f1_score:{f1_score(Ytest,Yest_lgr)}")

confusion_matrix:
 [[71  1]
 [ 2 40]]
accuracy_score:0.9736842105263158
precision_score:0.975609756097561
recall_score:0.9523809523809523
f1_score:0.963855421686747


In [17]:
### score:Returns the mean accuracy on the given data and labels
print(f"Training set score of logistic model:{lgr.score(Xtrain,Ytrain)}")
print(f"Testing set score logistic model:{lgr.score(Xtest,Ytest)}")

Training set score of logistic model:0.9912087912087912
Testing set score logistic model:0.9736842105263158


# 2.Naive Baye's method

###### step.1:Training the model

In [18]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(Xtrain,Ytrain)

GaussianNB()

###### step.2:Testind the model

In [19]:
Yest_nb=nb.predict(Xtest)
print(np.concatenate((Ytest.reshape(len(Ytest),1),Yest_nb.reshape(len(Yest_nb),1)),1))

[[0 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]]


###### step.3:Finding Error

In [20]:
print(f"Mean Absolute Error of the NB model is given as:{mean_absolute_error(Ytest,Yest_nb)}")
print(f"Mean Squared Error of the NB model is given as:{mean_squared_error(Ytest,Yest_nb)}")
print(f"Root Mean Squared Error of the NB model is given as:{np.sqrt(mean_squared_error(Ytest,Yest_nb))}")

Mean Absolute Error of the NB model is given as:0.05263157894736842
Mean Squared Error of the NB model is given as:0.05263157894736842
Root Mean Squared Error of the NB model is given as:0.22941573387056177


###### step.4:Finding score/accuracy

In [21]:
print(f"confusion_matrix:\n {confusion_matrix(Ytest,Yest_nb)}")
print(f"accuracy_score:{accuracy_score(Ytest,Yest_nb)}")
print(f"precision_score:{precision_score(Ytest,Yest_nb)}")
print(f"recall_score:{recall_score(Ytest,Yest_nb)}")
print(f"f1_score:{f1_score(Ytest,Yest_nb)}")

confusion_matrix:
 [[70  2]
 [ 4 38]]
accuracy_score:0.9473684210526315
precision_score:0.95
recall_score:0.9047619047619048
f1_score:0.9268292682926829


In [22]:
### score:Returns the mean accuracy on the given data and labels
print(f"Training set score of NB model:{nb.score(Xtrain,Ytrain)}")
print(f"Testing set score NB model:{nb.score(Xtest,Ytest)}")

Training set score of NB model:0.9340659340659341
Testing set score NB model:0.9473684210526315


# 3.Decision Tree

###### step.1:Training the model

In [23]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier(criterion='entropy',max_depth=3)
dt.fit(Xtrain,Ytrain)

DecisionTreeClassifier(criterion='entropy', max_depth=3)

###### step.2:Testind the model

In [24]:
Yest_dt=dt.predict(Xtest)
print(np.concatenate((Ytest.reshape(len(Ytest),1),Yest_dt.reshape(len(Yest_dt),1)),1))

[[0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]]


###### step.3:Finding Error

In [25]:
print(f"Mean Absolute Error of the decision tree model is given as:{mean_absolute_error(Ytest,Yest_dt)}")
print(f"Mean Squared Error of the decision tree model is given as:{mean_squared_error(Ytest,Yest_dt)}")
print(f"Root Mean Squared Error of the decision tree model is given as:{np.sqrt(mean_squared_error(Ytest,Yest_dt))}")

Mean Absolute Error of the decision tree model is given as:0.08771929824561403
Mean Squared Error of the decision tree model is given as:0.08771929824561403
Root Mean Squared Error of the decision tree model is given as:0.2961744388795462


###### step.4:Finding score/accuracy

In [26]:
print(f"confusion_matrix:\n {confusion_matrix(Ytest,Yest_dt)}")
print(f"accuracy_score:{accuracy_score(Ytest,Yest_dt)}")
print(f"precision_score:{precision_score(Ytest,Yest_dt)}")
print(f"recall_score:{recall_score(Ytest,Yest_dt)}")
print(f"f1_score:{f1_score(Ytest,Yest_dt)}")

confusion_matrix:
 [[67  5]
 [ 5 37]]
accuracy_score:0.9122807017543859
precision_score:0.8809523809523809
recall_score:0.8809523809523809
f1_score:0.8809523809523809


In [27]:
### score:Returns the mean accuracy on the given data and labels
print(f"Training set score of DT model:{dt.score(Xtrain,Ytrain)}")
print(f"Testing set score of DT model:{dt.score(Xtest,Ytest)}")

Training set score of DT model:0.9648351648351648
Testing set score of DT model:0.9122807017543859


# 4.Random forest

###### step.1:Training the model

In [28]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=700,criterion='entropy')
rf.fit(Xtrain,Ytrain)

RandomForestClassifier(criterion='entropy', n_estimators=700)

###### step.2:Testind the model

In [29]:
Yest_rf=rf.predict(Xtest)
print(np.concatenate((Ytest.reshape(len(Ytest),1),Yest_rf.reshape(len(Yest_rf),1)),1))

[[0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]]


###### step.3:Finding Error

In [30]:
print(f"Mean Absolute Error of the Random forest model is given as:{mean_absolute_error(Ytest,Yest_rf)}")
print(f"Mean Squared Error of the Random forest model is given as:{mean_squared_error(Ytest,Yest_rf)}")
print(f"Root Mean Squared Error of the Random forest model is given as:{np.sqrt(mean_squared_error(Ytest,Yest_rf))}")

Mean Absolute Error of the Random forest model is given as:0.043859649122807015
Mean Squared Error of the Random forest model is given as:0.043859649122807015
Root Mean Squared Error of the Random forest model is given as:0.20942695414584775


###### step.4:Finding score/accuracy

In [31]:
print(f"confusion_matrix:\n {confusion_matrix(Ytest,Yest_rf)}")
print(f"accuracy_score:{accuracy_score(Ytest,Yest_rf)}")
print(f"precision_score:{precision_score(Ytest,Yest_rf)}")
print(f"recall_score:{recall_score(Ytest,Yest_rf)}")
print(f"f1_score:{f1_score(Ytest,Yest_rf)}")

confusion_matrix:
 [[72  0]
 [ 5 37]]
accuracy_score:0.956140350877193
precision_score:1.0
recall_score:0.8809523809523809
f1_score:0.9367088607594937


In [32]:
### score:Returns the mean accuracy on the given data and labels
print(f"Training set score:{rf.score(Xtrain,Ytrain)}")
print(f"Testing set score:{rf.score(Xtest,Ytest)}")

Training set score:1.0
Testing set score:0.956140350877193


# 5.KNN Classification Algorithm

###### step.1:Training the model

In [33]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=20)
knn.fit(Xtrain,Ytrain)

KNeighborsClassifier(n_neighbors=20)

###### step.2:Testind the model

In [34]:
Yest_knn=knn.predict(Xtest)
print(np.concatenate((Ytest.reshape(len(Ytest),1),Yest_knn.reshape(len(Yest_knn),1)),1))

[[0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]]


###### step.3:Finding Error

In [35]:
print(f"Mean Absolute Error of the KNN model is given as:{mean_absolute_error(Ytest,Yest_rf)}")
print(f"Mean Squared Error of the KNN model is given as:{mean_squared_error(Ytest,Yest_rf)}")
print(f"Root Mean Squared Error of the KNN model is given as:{np.sqrt(mean_squared_error(Ytest,Yest_rf))}")

Mean Absolute Error of the KNN model is given as:0.043859649122807015
Mean Squared Error of the KNN model is given as:0.043859649122807015
Root Mean Squared Error of the KNN model is given as:0.20942695414584775


###### step.4:Finding score/accuracy

In [36]:
print(f"confusion_matrix:\n {confusion_matrix(Ytest,Yest_knn)}")
print(f"accuracy_score:{accuracy_score(Ytest,Yest_knn)}")
print(f"precision_score:{precision_score(Ytest,Yest_knn)}")
print(f"recall_score:{recall_score(Ytest,Yest_knn)}")
print(f"f1_score:{f1_score(Ytest,Yest_knn)}")

confusion_matrix:
 [[72  0]
 [ 6 36]]
accuracy_score:0.9473684210526315
precision_score:1.0
recall_score:0.8571428571428571
f1_score:0.923076923076923


In [37]:
### score:Returns the mean accuracy on the given data and labels
print(f"Training set score:{knn.score(Xtrain,Ytrain)}")
print(f"Testing set score:{knn.score(Xtest,Ytest)}")

Training set score:0.9604395604395605
Testing set score:0.9473684210526315


## Accuracy_score of All method

In [38]:
print(f"accuracy_score of LGR model:{accuracy_score(Ytest,Yest_lgr)}")
print(f"accuracy_score of NB model:{accuracy_score(Ytest,Yest_nb)}")
print(f"accuracy_score of DT model:{accuracy_score(Ytest,Yest_dt)}")
print(f"accuracy_score of RF model:{accuracy_score(Ytest,Yest_rf)}")
print(f"accuracy_score of KNN model:{accuracy_score(Ytest,Yest_knn)}")

accuracy_score of LGR model:0.9736842105263158
accuracy_score of NB model:0.9473684210526315
accuracy_score of DT model:0.9122807017543859
accuracy_score of RF model:0.956140350877193
accuracy_score of KNN model:0.9473684210526315
